name: "fae9ba13_local_triton_nnop_postprocess"
backend: "python"
max_batch_size: 0

input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [-1, 512]
  }
]

output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [512]
  }
]
