# -*- coding: utf-8 -*-
# pylint: skip-file
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x80\x01\n\x07\x43ontent\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12\x19\n\x06tensor\x18\x02 \x01(\x0b\x32\x07.TensorH\x00\x12&\n\x04json\x18\x03 \x01(\x0b\x32\x16.google.protobuf.ValueH\x00\x12\x17\n\rcontent_bytes\x18\x04 \x01(\x0cH\x00\x42\t\n\x07\x63ontent\"2\n\x07Request\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x19\n\x07\x63ontent\x18\x02 \x01(\x0b\x32\x08.Content\"@\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x19\n\x07\x63ontent\x18\x03 \x01(\x0b\x32\x08.Content\"E\n\x06Tensor\x12\r\n\x05\x64type\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x1d\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x0f.TensorContents\"\xdf\x01\n\x0eTensorContents\x12\x15\n\rstring_values\x18\x01 \x03(\t\x12\x18\n\x0c\x66loat_values\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x19\n\rdouble_values\x18\x03 \x03(\x01\x42\x02\x10\x01\x12\x17\n\x0b\x62ool_values\x18\x04 \x03(\x08\x42\x02\x10\x01\x12\x18\n\x0cint32_values\x18\x05 \x03(\x05\x42\x02\x10\x01\x12\x18\n\x0cint64_values\x18\x06 \x03(\x03\x42\x02\x10\x01\x12\x19\n\ruint32_values\x18\x07 \x03(\rB\x02\x10\x01\x12\x19\n\ruint64_values\x18\x08 \x03(\x04\x42\x02\x10\x01\x32\x32\n\x10PipelineServices\x12\x1e\n\x07Predict\x12\x08.Request\x1a\t.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TENSORCONTENTS.fields_by_name['float_values']._options = None
  _TENSORCONTENTS.fields_by_name['float_values']._serialized_options = b'\020\001'
  _TENSORCONTENTS.fields_by_name['double_values']._options = None
  _TENSORCONTENTS.fields_by_name['double_values']._serialized_options = b'\020\001'
  _TENSORCONTENTS.fields_by_name['bool_values']._options = None
  _TENSORCONTENTS.fields_by_name['bool_values']._serialized_options = b'\020\001'
  _TENSORCONTENTS.fields_by_name['int32_values']._options = None
  _TENSORCONTENTS.fields_by_name['int32_values']._serialized_options = b'\020\001'
  _TENSORCONTENTS.fields_by_name['int64_values']._options = None
  _TENSORCONTENTS.fields_by_name['int64_values']._serialized_options = b'\020\001'
  _TENSORCONTENTS.fields_by_name['uint32_values']._options = None
  _TENSORCONTENTS.fields_by_name['uint32_values']._serialized_options = b'\020\001'
  _TENSORCONTENTS.fields_by_name['uint64_values']._options = None
  _TENSORCONTENTS.fields_by_name['uint64_values']._serialized_options = b'\020\001'
  _CONTENT._serialized_start=48
  _CONTENT._serialized_end=176
  _REQUEST._serialized_start=178
  _REQUEST._serialized_end=228
  _RESPONSE._serialized_start=230
  _RESPONSE._serialized_end=294
  _TENSOR._serialized_start=296
  _TENSOR._serialized_end=365
  _TENSORCONTENTS._serialized_start=368
  _TENSORCONTENTS._serialized_end=591
  _PIPELINESERVICES._serialized_start=593
  _PIPELINESERVICES._serialized_end=643
# @@protoc_insertion_point(module_scope)
