name: "fae9ba13_local_triton_nnop_model"
backend: "tensorrt"
max_batch_size: 0

input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [-1, 3, 224, 224]
  }
]

output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [-1, 512]
  }
]
