name: "db5377c3_local_triton_nnop_model"
backend: "tensorrt"
max_batch_size: 128

dynamic_batching {

    preferred_batch_size: [1, 2]

    max_queue_delay_microseconds: 10000

}

input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [3, 224, 224]
  }
]

output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [512]
  }
]

instance_group [
    {
        kind: KIND_GPU
        count: 2
        gpus: [1, 2]
    }
]
