name: Publish Towhee.models to TestPyPI
on:
  pull_request:
    branches:
      - main
      # file paths to consider in the event
    paths:
      - '.github/workflows/publish_model_package.yml'
  push:
    branches:
      - 'main'
    paths:
      - 'towhee/models/**'
      - '.github/workflows/publish_model_package.yml'
jobs:
  build-n-publish:
    name: Build and Publish Towhee.models to TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.8
    - name: Get history and tags for SCM versioning
      run: |
          git fetch --prune --unshallow
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Run Test
      run: |
        cd  tests/testcases
        python3 -m pip install -U pip
        python3 -m pip install --no-cache-dir -r requirements.text
        export TOWHEE_WORKER=True
        python3 -W ignore test_main.py
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python
        setup.py
        --models
        bdist_wheel
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: "zhujiming"
        password: "zhu5271011"
        repository_url: https://test.pypi.org/legacy/